name: Deploy to EKS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [1-infra, 2-build]
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download kubeconfig
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: /tmp

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          cp /tmp/kubeconfig.yaml ~/.kube/config
          kubectl version --client

      - name: Download image info
        uses: actions/download-artifact@v3
        with:
          name: image-info
          path: /tmp

      - name: Set image tag
        id: image
        run: |
          echo "image=$(cat /tmp/image-info)" >> $GITHUB_OUTPUT

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Install Helm Chart
        run: |
          helm upgrade --install webserver ./charts/webserver \
            --namespace webserver \
            --create-namespace \
            --set image.repository=${{ steps.image.outputs.image }}

      - name: Verify Deployment
        run: |
          kubectl get pods -n webserver
          kubectl get svc -n webserver