replicaCount: 2

image:
  repository: 748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx-2
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer  # Changed from ClusterIP to expose externally
  port: 80
  targetPort: 80

# REMOVED: Entire 'ingress' section