replicaCount: 2

image:
  repository: 748852117020.dkr.ecr.us-west-2.amazonaws.com/cyderes-webserver
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cyderes-challenge.example.com
      paths:
        - path: /
          pathType: Prefix