replicaCount: 2

image:
  repository: <your-ecr-uri>  # Example: 123456789.dkr.ecr.us-west-2.amazonaws.com/cyderes-nginx
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: web.local
      paths:
        - path: /
          pathType: Prefix

resources: {}
