replicaCount: 2

image:
  repository: 748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx-2
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP  # Overridden by --set in workflow
  port: 80
  targetPort: 80
  annotations: {}  # Will be set in workflow