# charts/webserver/values.yaml

replicaCount: 2

image:
  repository: 748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx-2
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-06a484632a8634a3b,subnet-033ecfe85b7d4b118,subnet-0c8ecd18b7031caf9,subnet-082b19f50553eabaf" # Replace with your actual subnet IDs

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

tolerations:
- key: "CriticalAddonsOnly"
  operator: "Exists"
  effect: "NoSchedule"

nodeSelector: {}

affinity: {}

# Optional: For ECR access
imagePullSecrets: []
# - name: ecr-credentials