apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default "nginx" }}
  labels:
    app: {{ .Values.nameOverride | default "nginx" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride | default "nginx" }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride | default "nginx" }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.nameOverride | default "nginx" }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}