name: Provision EKS Infrastructure

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="github_org=${{ github.repository_owner }}" \
            -var="github_repo=${{ github.event.repository.name }}"

      - name: Configure kubectl
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig \
            --name $(terraform -chdir=terraform output -raw cluster_name)
          kubectl config view --minify --flatten > kubeconfig.yaml

      - name: Upload kubeconfig
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: kubeconfig.yaml