name: Deploy to Kubernetes

on:
  push:
    paths:
      - 'charts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install webserver charts/webserver --namespace default
