name: Deploy to EKS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  CLUSTER_NAME: funny-synth-duck
  ECR_REPO: 748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.CLUSTER_NAME }}

      - name: Tag subnets (required for LoadBalancer)
        run: |
          SUBNETS=$(aws eks describe-cluster --name ${{ env.CLUSTER_NAME }} --query "cluster.resourcesVpcConfig.subnetIds" --output text)
          aws ec2 create-tags --resources $SUBNETS \
            --tags Key=kubernetes.io/role/elb,Value=1 Key=kubernetes.io/role/internal-elb,Value=1

      - name: Deploy Helm chart
        run: |
          # Get subnets as JSON array
          SUBNETS_JSON=$(aws eks describe-cluster --name ${{ env.CLUSTER_NAME }} \
            --query "cluster.resourcesVpcConfig.subnetIds" \
            --output json)
          
          helm upgrade --install webserver ./charts/webserver \
            --namespace cyderes \
            --create-namespace \
            --set service.type=LoadBalancer \
            --set service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-scheme"=internet-facing \
            --set-json service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-subnets"="$SUBNETS_JSON" \
            --set image.repository=${{ env.ECR_REPO }} \
            --set image.tag=latest \
            --atomic \
            --timeout 5m

      - name: Verify deployment
        run: |
          echo "LoadBalancer URL:"
          kubectl get svc webserver -n cyderes -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
          echo -e "\nPods:"
          kubectl get pods -n cyderes