name: Deploy to EKS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  CLUSTER_NAME: funny-synth-duck
  ECR_REPO: 748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install webserver ./charts/webserver \
            --namespace cyderes \
            --create-namespace \
            --atomic \
            --timeout 5m \
            --set image.repository=${{ env.ECR_REPO }} \
            --set image.tag=latest