name: Docker Hub Deployment

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: avil172/my-nginx

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: avil172
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to k3s
        run: |
          ssh -i ~/.ssh/ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            # Pre-pull image to ensure availability
            sudo k3s crictl pull docker.io/$DOCKER_IMAGE:latest
            
            helm upgrade --install nginx ./charts/nginx \
              --set image.repository="avil172/my-nginx" \
              --set image.pullPolicy="Always" \
              --atomic \
              --timeout 5m
          EOF

      - name: Verify
        run: |
          ssh -i ~/.ssh/ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            kubectl get pods -o wide
            curl -s http://localhost:30080 | grep "Successfully Deployed" || echo "Content verification failed"
          EOF