name: Deploy to k3s

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code (contains Helm charts)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure SSH access to EC2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          echo "${{ secrets.EC2_PUBLIC_IP }} ssh-ed25519 AAAAC3..." >> ~/.ssh/known_hosts

      # 3. Copy Helm charts to EC2
      - name: Transfer Helm charts
        run: |
          scp -i ~/.ssh/ec2_key.pem -r ./charts/nginx ec2-user@${{ secrets.EC2_PUBLIC_IP }}:~/nginx-chart

      # 4. Remote deployment using EC2's native kubeconfig
      - name: Execute Helm deployment
        run: |
          ssh -i ~/.ssh/ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Use the server's built-in kubeconfig
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            
            # Deploy using the copied chart
            helm upgrade --install nginx ~/nginx-chart \
              --set image.repository=748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx-2 \
              --set image.tag=latest \
              --atomic \
              --timeout 5m0s
            
            # Verify deployment
            kubectl get pods -n default
          EOF

      # 5. Cleanup (optional)
      - name: Remove SSH key
        if: always()
        run: rm -f ~/.ssh/ec2_key.pem