name: Deploy to k3s

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.25.0'  # Matches your k3s version

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.10.0'

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config
        kubectl config set-cluster k3s --insecure-skip-tls-verify=true
        kubectl get nodes  # Verify cluster access

    - name: Deploy with Helm
      run: |
        helm upgrade --install nginx ./charts/nginx \
          --set image.repository=748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx-2 \
          --set image.tag=latest \
          --atomic \
          --timeout 5m0s