name: Deploy to k3s

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          # Pre-verify host key
          ssh-keyscan -H "${{ secrets.EC2_PUBLIC_IP }}" >> ~/.ssh/known_hosts

      - name: Transfer Helm charts
        run: |
          # Create destination directory first
          ssh -i ~/.ssh/ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p ~/nginx-chart"
          # Use rsync for more reliable transfers
          rsync -avz -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=yes" \
            ./charts/nginx/ \
            ec2-user@${{ secrets.EC2_PUBLIC_IP }}:~/nginx-chart/

      - name: Remote Helm deployment
        run: |
          ssh -i ~/.ssh/ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            helm upgrade --install nginx ~/nginx-chart \
              --set image.repository=748852117020.dkr.ecr.us-west-2.amazonaws.com/devops/cyderes-nginx-2 \
              --set image.tag=latest \
              --atomic \
              --timeout 5m0s
            kubectl get pods
          EOF

      - name: Cleanup
        if: always()
        run: rm -f ~/.ssh/ec2_key.pem