name: Manual GKE Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy test image to GKE
      run: |
        kubectl create deployment hello --image=nginxdemos/hello || kubectl rollout restart deployment hello
        kubectl expose deployment hello --type=LoadBalancer --port 80 || echo "Service may already exist"
        kubectl get svc hello
